CREATE DATABASE IF NOT EXISTS formation_humaine_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE formation_humaine_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS ANNEE_ACADEMIQUE, APPEL, CLUB, CRITERE, DEPARTEMENT, 
                  DOMAINE, ENSEIGNANT, ETUDIANT, FILIERE, JOURNAL_CONNEXION, 
                  JUSTIFICATION_ABSENCE, MOUVEMENT_POINTS, NIVEAU, 
                  PERSONNEL_ADMINISTRATIF, PIECE_JUSTIFICATIVE, PRESENCE, 
                  PROMOTION, RESULTAT_SEMESTRIEL, ROLE, SEANCE, SEMESTRE, 
                  SIGNALEMENT, PERSONNE;

SET FOREIGN_KEY_CHECKS = 1;

-- 1. ROLE
CREATE TABLE ROLE (
   ID_ROLE INT AUTO_INCREMENT PRIMARY KEY,
   CODE_ROLE VARCHAR(30) NOT NULL,
   LIBELLE_CRITERE VARCHAR(100)
) ENGINE=InnoDB;

-- 2. CLUB
CREATE TABLE CLUB (
   ID_CLUB INT AUTO_INCREMENT PRIMARY KEY,
   NOM_CLUB VARCHAR(100) NOT NULL,
   DESCRIPTION LONGTEXT
) ENGINE=InnoDB;

-- 3. DEPARTEMENT
CREATE TABLE DEPARTEMENT (
   ID_DEPT INT AUTO_INCREMENT PRIMARY KEY,
   CODE_DEPT VARCHAR(50) NOT NULL,
   NOM_DEPT VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

-- 4. DOMAINE
CREATE TABLE DOMAINE (
   ID_DOMAINE INT AUTO_INCREMENT PRIMARY KEY,
   NOM_DOMAINE VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

-- 5. ANNEE_ACADEMIQUE
CREATE TABLE ANNEE_ACADEMIQUE (
   ID_ANNEE INT AUTO_INCREMENT PRIMARY KEY,
   LIBELLE_ANNEE VARCHAR(20) NOT NULL,
   DATE_SEANCE DATE NOT NULL,
   HEURE_DEBUT TIME NOT NULL
) ENGINE=InnoDB;

-- 6. NIVEAU
CREATE TABLE NIVEAU (
   ID_NIVEAU INT AUTO_INCREMENT PRIMARY KEY,
   CODE_NIVEAU VARCHAR(20) NOT NULL,
   LIBELLE_CRITERE VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

-- 7. PROMOTION
CREATE TABLE PROMOTION (
   ID_PROMO INT AUTO_INCREMENT PRIMARY KEY,
   ID_ANNEE INT NOT NULL,
   ID_NIVEAU INT NOT NULL,
   CODE_PROMO VARCHAR(50) NOT NULL,
   EFFECTIF_PROMO BIGINT NOT NULL,
   CONSTRAINT FK_CADRER FOREIGN KEY (ID_ANNEE) REFERENCES ANNEE_ACADEMIQUE (ID_ANNEE),
   CONSTRAINT FK_STRUCTURER FOREIGN KEY (ID_NIVEAU) REFERENCES NIVEAU (ID_NIVEAU)
) ENGINE=InnoDB;

-- 8. FILIERE
CREATE TABLE FILIERE (
   ID_FILIERE INT AUTO_INCREMENT PRIMARY KEY,
   ID_DEPT INT NOT NULL,
   ID_PROMO INT NOT NULL,
   CODE_FILIERE VARCHAR(50) NOT NULL,
   NOM_FILIERE VARCHAR(100) NOT NULL,
   CONSTRAINT FK_RATTACHER FOREIGN KEY (ID_DEPT) REFERENCES DEPARTEMENT (ID_DEPT),
   CONSTRAINT FK_COMPOSER FOREIGN KEY (ID_PROMO) REFERENCES PROMOTION (ID_PROMO)
) ENGINE=InnoDB;

-- 9. PERSONNE
CREATE TABLE PERSONNE (
   ID_PERSONNE INT AUTO_INCREMENT PRIMARY KEY,
   ID_ROLE INT NOT NULL,
   NOM VARCHAR(50) NOT NULL,
   PRENOM VARCHAR(50) NOT NULL,
   EMAIL VARCHAR(100) NOT NULL UNIQUE,
   MOT_DE_PASSE VARCHAR(255) NOT NULL,
   TELEPHONE VARCHAR(100) NOT NULL,
   SEXE VARCHAR(5) NOT NULL,
   DATE_NAISSANCE DATE NOT NULL,
   ADRESSE VARCHAR(100),
   PHOTO VARCHAR(255),
   STATUT_COMPTE VARCHAR(50) NOT NULL DEFAULT 'ACTIF',
   DATE_CREATION DATETIME DEFAULT CURRENT_TIMESTAMP,
   MATRICULE VARCHAR(50) NOT NULL UNIQUE,
   CONSTRAINT FK_POSSEDER_ROLE FOREIGN KEY (ID_ROLE) REFERENCES ROLE (ID_ROLE)
) ENGINE=InnoDB;

-- 10. ETUDIANT
CREATE TABLE ETUDIANT (
   ID_PERSONNE INT PRIMARY KEY,
   ID_PROMO INT NOT NULL,
   ID_CLUB INT NULL,
   CONSTRAINT FK_ETUDIANT_PERSONNE FOREIGN KEY (ID_PERSONNE) REFERENCES PERSONNE (ID_PERSONNE) ON DELETE CASCADE,
   CONSTRAINT FK_S_INSCRIRE FOREIGN KEY (ID_PROMO) REFERENCES PROMOTION (ID_PROMO),
   CONSTRAINT FK_ADHERER FOREIGN KEY (ID_CLUB) REFERENCES CLUB (ID_CLUB)
) ENGINE=InnoDB;

-- 11. ENSEIGNANT
CREATE TABLE ENSEIGNANT (
   ID_PERSONNE INT PRIMARY KEY,
   GRADE VARCHAR(255) NOT NULL,
   DOMAINE VARCHAR(100) NOT NULL,
   CONSTRAINT FK_ENSEIGNANT_PERSONNE FOREIGN KEY (ID_PERSONNE) REFERENCES PERSONNE (ID_PERSONNE) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 12. PERSONNEL_ADMINISTRATIF
CREATE TABLE PERSONNEL_ADMINISTRATIF (
   ID_PERSONNE INT PRIMARY KEY,
   POSTE VARCHAR(100) NOT NULL,
   CONSTRAINT FK_ADMIN_PERSONNE FOREIGN KEY (ID_PERSONNE) REFERENCES PERSONNE (ID_PERSONNE) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 13. CRITERE
CREATE TABLE CRITERE (
   ID_CRITERE INT AUTO_INCREMENT PRIMARY KEY,
   ID_DOMAINE INT NOT NULL,
   LIBELLE_CRITERE VARCHAR(100) NOT NULL,
   VALEUR_POINTS INT NOT NULL,
   CONSTRAINT FK_REGROUPER FOREIGN KEY (ID_DOMAINE) REFERENCES DOMAINE (ID_DOMAINE) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 14. SEMESTRE
CREATE TABLE SEMESTRE (
   ID_SEMESTRE INT AUTO_INCREMENT PRIMARY KEY,
   ID_ANNEE INT NOT NULL,
   CODE_SEMESTRE VARCHAR(20) NOT NULL,
   LIBELLE_SEMESTRE VARCHAR(50),
   DATE_SEANCE DATE NOT NULL,
   HEURE_DEBUT TIME NOT NULL,
   CONSTRAINT FK_DECOUPER FOREIGN KEY (ID_ANNEE) REFERENCES ANNEE_ACADEMIQUE (ID_ANNEE)
) ENGINE=InnoDB;

-- 15. SEANCE
CREATE TABLE SEANCE (
   ID_SEANCE INT AUTO_INCREMENT PRIMARY KEY,
   ID_CLUB INT NOT NULL,
   TITRE_SEANCE VARCHAR(100) NOT NULL,
   DATE_SEANCE DATE NOT NULL,
   HEURE_DEBUT TIME NOT NULL,
   DATE_FIN TIME NOT NULL,
   LIEU VARCHAR(50) NOT NULL,
   CONSTRAINT FK_ORGANISER FOREIGN KEY (ID_CLUB) REFERENCES CLUB (ID_CLUB)
) ENGINE=InnoDB;

-- 16. APPEL
CREATE TABLE APPEL (
   ID_APPEL INT AUTO_INCREMENT PRIMARY KEY,
   ID_SEANCE INT NOT NULL,
   DATE_APPEL DATETIME DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT FK_CREER_APPEL FOREIGN KEY (ID_SEANCE) REFERENCES SEANCE (ID_SEANCE) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 17. PRESENCE
CREATE TABLE PRESENCE (
   ID_PRESENCE INT AUTO_INCREMENT PRIMARY KEY,
   ID_APPEL INT NOT NULL,
   ID_PERSONNE INT NOT NULL,
   STATUT VARCHAR(20) NOT NULL,
   CONSTRAINT FK_PRESENCE_ETUDIANT FOREIGN KEY (ID_PERSONNE) REFERENCES ETUDIANT (ID_PERSONNE),
   CONSTRAINT FK_PRESENCE_APPEL FOREIGN KEY (ID_APPEL) REFERENCES APPEL (ID_APPEL) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 18. JUSTIFICATION_ABSENCE
CREATE TABLE JUSTIFICATION_ABSENCE (
   ID_JUSTIFICATION INT AUTO_INCREMENT PRIMARY KEY,
   ID_PRESENCE INT NOT NULL,
   MOTIF LONGTEXT NOT NULL,
   DATE_DEPOT DATETIME DEFAULT CURRENT_TIMESTAMP,
   STATUT_VALIDATION VARCHAR(100) NOT NULL DEFAULT 'EN_ATTENTE',
   CONSTRAINT FK_JUSTIFIER FOREIGN KEY (ID_PRESENCE) REFERENCES PRESENCE (ID_PRESENCE) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 19. SIGNALEMENT
CREATE TABLE SIGNALEMENT (
   ID_SIGNALEMENT INT AUTO_INCREMENT PRIMARY KEY,
   ETU_ID_PERSONNE INT NOT NULL,
   PER_ID_PERSONNE INT NULL,
   TITRE_SEANCE VARCHAR(100) NOT NULL,
   DESCRIPTION LONGTEXT NOT NULL,
   DATE_SIGNALEMENT DATETIME DEFAULT CURRENT_TIMESTAMP,
   LIEU_SIGNALEMENT VARCHAR(255) NOT NULL,
   STATUT VARCHAR(20) NOT NULL DEFAULT 'NOUVEAU',
   CONSTRAINT FK_DECLARER_ETU FOREIGN KEY (ETU_ID_PERSONNE) REFERENCES ETUDIANT (ID_PERSONNE),
   CONSTRAINT FK_VALIDER_ADMIN FOREIGN KEY (PER_ID_PERSONNE) REFERENCES PERSONNEL_ADMINISTRATIF (ID_PERSONNE)
) ENGINE=InnoDB;

-- 20. PIECE_JUSTIFICATIVE
CREATE TABLE PIECE_JUSTIFICATIVE (
   ID_PIECE INT AUTO_INCREMENT PRIMARY KEY,
   ID_SIGNALEMENT INT NOT NULL,
   NOM_FICHIER VARCHAR(100) NOT NULL,
   CHEMIN_FICHIER VARCHAR(255) NOT NULL,
   TYPE_FICHIER VARCHAR(50) NOT NULL,
   CONSTRAINT FK_JOINDRE FOREIGN KEY (ID_SIGNALEMENT) REFERENCES SIGNALEMENT (ID_SIGNALEMENT) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 21. MOUVEMENT_POINTS
CREATE TABLE MOUVEMENT_POINTS (
   ID_MOUVEMENT INT AUTO_INCREMENT PRIMARY KEY,
   ID_CRITERE INT NOT NULL,
   ID_PERSONNE INT NOT NULL,
   NOMBRE_POINTS DECIMAL(5,2) NOT NULL,
   DATE_MOUVEMENT DATETIME DEFAULT CURRENT_TIMESTAMP,
   MOTIF_MOUVEMENT VARCHAR(255),
   TYPE_MOUVEMENT VARCHAR(10),
   CONSTRAINT FK_MOTIVER FOREIGN KEY (ID_CRITERE) REFERENCES CRITERE (ID_CRITERE),
   CONSTRAINT FK_POINTS_ETUDIANT FOREIGN KEY (ID_PERSONNE) REFERENCES ETUDIANT (ID_PERSONNE)
) ENGINE=InnoDB;

-- 22. RESULTAT_SEMESTRIEL
CREATE TABLE RESULTAT_SEMESTRIEL (
   ID_RESULTAT INT AUTO_INCREMENT PRIMARY KEY,
   ID_SEMESTRE INT NOT NULL,
   ID_PERSONNE INT NOT NULL,
   MOYENNE DECIMAL(4,2) NOT NULL,
   MENTION VARCHAR(50),
   STATUT_VALIDATION VARCHAR(100) NOT NULL,
   CONSTRAINT FK_GENERER FOREIGN KEY (ID_SEMESTRE) REFERENCES SEMESTRE (ID_SEMESTRE),
   CONSTRAINT FK_RESULTAT_ETUDIANT FOREIGN KEY (ID_PERSONNE) REFERENCES ETUDIANT (ID_PERSONNE)
) ENGINE=InnoDB;

-- 23. JOURNAL_CONNEXION
CREATE TABLE JOURNAL_CONNEXION (
   ID_JOURNAL INT AUTO_INCREMENT PRIMARY KEY,
   ID_PERSONNE INT NOT NULL,
   DATE_CONNEXION DATETIME DEFAULT CURRENT_TIMESTAMP,
   ADESSE_IP VARCHAR(50) NOT NULL,
   STATUT VARCHAR(20) NOT NULL,
   CONSTRAINT FK_TRACER_PERSONNE FOREIGN KEY (ID_PERSONNE) REFERENCES PERSONNE (ID_PERSONNE) ON DELETE CASCADE
) ENGINE=InnoDB;
