CREATE DATABASE IF NOT EXISTS formation_humaine_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE formation_humaine_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS PARAMETRE_SYSTEME, TENTATIVE_CONNEXION, JOURNAL_CONNEXION, RESULTAT_SEMESTRIEL,
                     MOUVEMENT_POINTS, PIECE_JUSTIFICATIVE, TEMOIN, SIGNALEMENT_HISTORIQUE, SIGNALEMENT,
                     JUSTIFICATION_ABSENCE, PRESENCE, APPEL, SEANCE, CRITERE, DOMAINE,
                     PERSONNEL_ADMINISTRATIF, ENSEIGNANT, ETUDIANT, CLUB, PERSONNE,
                     PROMOTION, FILIERE, SEMESTRE, ANNEE_ACADEMIQUE, NIVEAU,
                     DEPARTEMENT, ROLE;

SET FOREIGN_KEY_CHECKS = 1;

-- 1. ROLE
CREATE TABLE ROLE (
   ID_ROLE INT AUTO_INCREMENT PRIMARY KEY,
   CODE_ROLE VARCHAR(30) NOT NULL UNIQUE,
   LIBELLE_ROLE VARCHAR(100)
) ENGINE=InnoDB;

-- 2. DEPARTEMENT
CREATE TABLE DEPARTEMENT (
   ID_DEPT INT AUTO_INCREMENT PRIMARY KEY,
   CODE_DEPT VARCHAR(50) NOT NULL,
   NOM_DEPT VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

-- 3. NIVEAU
CREATE TABLE NIVEAU (
   ID_NIVEAU INT AUTO_INCREMENT PRIMARY KEY,
   CODE_NIVEAU VARCHAR(20) NOT NULL,
   LIBELLE_NIVEAU VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

-- 4. ANNEE_ACADEMIQUE
CREATE TABLE ANNEE_ACADEMIQUE (
   ID_ANNEE INT AUTO_INCREMENT PRIMARY KEY,
   LIBELLE_ANNEE VARCHAR(20) NOT NULL,
   DATE_DEBUT DATE NOT NULL,
   DATE_FIN DATE NOT NULL
) ENGINE=InnoDB;

-- 5. SEMESTRE
CREATE TABLE SEMESTRE (
   ID_SEMESTRE INT AUTO_INCREMENT PRIMARY KEY,
   ID_ANNEE INT NOT NULL,
   CODE_SEMESTRE VARCHAR(20) NOT NULL,
   LIBELLE_SEMESTRE VARCHAR(50),
   DATE_DEBUT DATE NOT NULL,
   DATE_FIN DATE NOT NULL,
   CONSTRAINT FK_DECOUPER FOREIGN KEY (ID_ANNEE) REFERENCES ANNEE_ACADEMIQUE (ID_ANNEE)
) ENGINE=InnoDB;

-- 6. FILIERE
CREATE TABLE FILIERE (
   ID_FILIERE INT AUTO_INCREMENT PRIMARY KEY,
   ID_DEPT INT NOT NULL,
   CODE_FILIERE VARCHAR(50) NOT NULL,
   NOM_FILIERE VARCHAR(100) NOT NULL,
   CONSTRAINT FK_RATTACHER FOREIGN KEY (ID_DEPT) REFERENCES DEPARTEMENT (ID_DEPT)
) ENGINE=InnoDB;

-- 7. PROMOTION
CREATE TABLE PROMOTION (
   ID_PROMO INT AUTO_INCREMENT PRIMARY KEY,
   ID_ANNEE INT NOT NULL,
   ID_NIVEAU INT NOT NULL,
   ID_FILIERE INT NOT NULL,
   CODE_PROMO VARCHAR(50) NOT NULL,
   EFFECTIF_PROMO INT NOT NULL DEFAULT 0,
   CONSTRAINT FK_CADRER FOREIGN KEY (ID_ANNEE) REFERENCES ANNEE_ACADEMIQUE (ID_ANNEE),
   CONSTRAINT FK_STRUCTURER FOREIGN KEY (ID_NIVEAU) REFERENCES NIVEAU (ID_NIVEAU),
   CONSTRAINT FK_COMPOSER FOREIGN KEY (ID_FILIERE) REFERENCES FILIERE (ID_FILIERE)
) ENGINE=InnoDB;

-- 8. PERSONNE
CREATE TABLE PERSONNE (
   ID_PERSONNE INT AUTO_INCREMENT PRIMARY KEY,
   ID_ROLE INT NOT NULL,
   NOM VARCHAR(50) NOT NULL,
   PRENOM VARCHAR(50) NOT NULL,
   EMAIL VARCHAR(100) NOT NULL UNIQUE,
   MOT_DE_PASSE VARCHAR(255) NOT NULL,
   TELEPHONE VARCHAR(100) NOT NULL,
   SEXE VARCHAR(5) NOT NULL,
   DATE_NAISSANCE DATE NULL,
   ADRESSE VARCHAR(100),
   PHOTO VARCHAR(255),
   STATUT_COMPTE VARCHAR(50) NOT NULL DEFAULT 'ACTIF',
   DOIT_CHANGER_MDP TINYINT(1) NOT NULL DEFAULT 0,
   DATE_CREATION DATETIME DEFAULT CURRENT_TIMESTAMP,
   MATRICULE VARCHAR(50) NOT NULL UNIQUE,
   CONSTRAINT FK_POSSEDER_ROLE FOREIGN KEY (ID_ROLE) REFERENCES ROLE (ID_ROLE)
) ENGINE=InnoDB;

-- 9. CLUB
CREATE TABLE CLUB (
   ID_CLUB INT AUTO_INCREMENT PRIMARY KEY,
   NOM_CLUB VARCHAR(100) NOT NULL,
   DESCRIPTION LONGTEXT,
   ID_RESPONSABLE INT NULL,
   CONSTRAINT FK_CLUB_RESPONSABLE FOREIGN KEY (ID_RESPONSABLE) REFERENCES PERSONNE (ID_PERSONNE) ON DELETE SET NULL
) ENGINE=InnoDB;

-- 10. ETUDIANT
-- ID_PERSONNE reste la clé utilisée par toutes les tables liées à l'étudiant.
CREATE TABLE ETUDIANT (
   ID_ETUDIANT INT AUTO_INCREMENT PRIMARY KEY,
   ID_PERSONNE INT NOT NULL UNIQUE,
   ID_PROMO INT NOT NULL,
   ID_CLUB INT NULL,
   EST_DELEGUE TINYINT(1) NOT NULL DEFAULT 0,
   CONSTRAINT FK_ETUDIANT_PERSONNE FOREIGN KEY (ID_PERSONNE) REFERENCES PERSONNE (ID_PERSONNE) ON DELETE CASCADE,
   CONSTRAINT FK_S_INSCRIRE FOREIGN KEY (ID_PROMO) REFERENCES PROMOTION (ID_PROMO),
   CONSTRAINT FK_ADHERER FOREIGN KEY (ID_CLUB) REFERENCES CLUB (ID_CLUB) ON DELETE SET NULL
) ENGINE=InnoDB;

-- 11. ENSEIGNANT
CREATE TABLE ENSEIGNANT (
   ID_PERSONNE INT PRIMARY KEY,
   GRADE VARCHAR(255) NOT NULL,
   DOMAINE VARCHAR(100) NOT NULL,
   CONSTRAINT FK_ENSEIGNANT_PERSONNE FOREIGN KEY (ID_PERSONNE) REFERENCES PERSONNE (ID_PERSONNE) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 12. PERSONNEL_ADMINISTRATIF
CREATE TABLE PERSONNEL_ADMINISTRATIF (
   ID_PERSONNE INT PRIMARY KEY,
   POSTE VARCHAR(100) NOT NULL,
   CONSTRAINT FK_ADMIN_PERSONNE FOREIGN KEY (ID_PERSONNE) REFERENCES PERSONNE (ID_PERSONNE) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 13. DOMAINE
CREATE TABLE DOMAINE (
   ID_DOMAINE INT AUTO_INCREMENT PRIMARY KEY,
   CODE_DOMAINE VARCHAR(30) NOT NULL UNIQUE,
   NOM_DOMAINE VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

-- 14. CRITERE
-- VALEUR_POINTS est signée (ex : -0.25 pour un retard, +0.50 pour une action écologique).
CREATE TABLE CRITERE (
   ID_CRITERE INT AUTO_INCREMENT PRIMARY KEY,
   ID_DOMAINE INT NOT NULL,
   LIBELLE_CRITERE VARCHAR(100) NOT NULL,
   VALEUR_POINTS DECIMAL(4,2) NOT NULL,
   ACTIF TINYINT(1) NOT NULL DEFAULT 1,
   CONSTRAINT FK_REGROUPER FOREIGN KEY (ID_DOMAINE) REFERENCES DOMAINE (ID_DOMAINE)
) ENGINE=InnoDB;

-- 15. SEANCE
-- Une séance appartient soit à un club, soit à une promotion (appel par classe).
CREATE TABLE SEANCE (
   ID_SEANCE INT AUTO_INCREMENT PRIMARY KEY,
   ID_CLUB INT NULL,
   ID_PROMO INT NULL,
   TITRE_SEANCE VARCHAR(100) NOT NULL,
   DATE_SEANCE DATE NOT NULL,
   HEURE_DEBUT TIME NOT NULL,
   HEURE_FIN TIME NOT NULL,
   LIEU VARCHAR(50) NOT NULL,
   CONSTRAINT FK_ORGANISER FOREIGN KEY (ID_CLUB) REFERENCES CLUB (ID_CLUB),
   CONSTRAINT FK_SEANCE_PROMO FOREIGN KEY (ID_PROMO) REFERENCES PROMOTION (ID_PROMO)
) ENGINE=InnoDB;

-- 16. APPEL
CREATE TABLE APPEL (
   ID_APPEL INT AUTO_INCREMENT PRIMARY KEY,
   ID_SEANCE INT NOT NULL,
   ID_PERSONNE INT NULL,
   DATE_APPEL DATETIME DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT FK_CREER_APPEL FOREIGN KEY (ID_SEANCE) REFERENCES SEANCE (ID_SEANCE) ON DELETE CASCADE,
   CONSTRAINT FK_APPEL_AUTEUR FOREIGN KEY (ID_PERSONNE) REFERENCES PERSONNE (ID_PERSONNE) ON DELETE SET NULL
) ENGINE=InnoDB;

-- 17. PRESENCE
-- STATUT : PRESENT, RETARD, ABSENT, ABSENT_JUSTIFIE
CREATE TABLE PRESENCE (
   ID_PRESENCE INT AUTO_INCREMENT PRIMARY KEY,
   ID_APPEL INT NOT NULL,
   ID_PERSONNE INT NOT NULL,
   STATUT VARCHAR(20) NOT NULL,
   CONSTRAINT FK_PRESENCE_ETUDIANT FOREIGN KEY (ID_PERSONNE) REFERENCES ETUDIANT (ID_PERSONNE),
   CONSTRAINT FK_PRESENCE_APPEL FOREIGN KEY (ID_APPEL) REFERENCES APPEL (ID_APPEL) ON DELETE CASCADE,
   CONSTRAINT UQ_PRESENCE UNIQUE (ID_APPEL, ID_PERSONNE)
) ENGINE=InnoDB;

-- 18. JUSTIFICATION_ABSENCE
-- STATUT_VALIDATION : EN_ATTENTE, VALIDEE, REJETEE
CREATE TABLE JUSTIFICATION_ABSENCE (
   ID_JUSTIFICATION INT AUTO_INCREMENT PRIMARY KEY,
   ID_PRESENCE INT NOT NULL,
   MOTIF LONGTEXT NOT NULL,
   CHEMIN_FICHIER VARCHAR(255) NULL,
   DATE_DEPOT DATETIME DEFAULT CURRENT_TIMESTAMP,
   STATUT_VALIDATION VARCHAR(100) NOT NULL DEFAULT 'EN_ATTENTE',
   ID_VALIDATEUR INT NULL,
   DATE_VALIDATION DATETIME NULL,
   COMMENTAIRE_VALIDATION VARCHAR(255) NULL,
   CONSTRAINT FK_JUSTIFIER FOREIGN KEY (ID_PRESENCE) REFERENCES PRESENCE (ID_PRESENCE) ON DELETE CASCADE,
   CONSTRAINT FK_JUSTIF_VALIDATEUR FOREIGN KEY (ID_VALIDATEUR) REFERENCES PERSONNE (ID_PERSONNE) ON DELETE SET NULL
) ENGINE=InnoDB;

-- 19. SIGNALEMENT
-- STATUT : BROUILLON, SOUMIS, EN_EXAMEN, ETUDIANT_ENTENDU, VALIDE, REJETE, ANNULE, CLOTURE
CREATE TABLE SIGNALEMENT (
   ID_SIGNALEMENT INT AUTO_INCREMENT PRIMARY KEY,
   ID_PERSONNE_ETUDIANT INT NOT NULL,
   ID_PERSONNE_AUTEUR INT NOT NULL,
   ID_PERSONNE_VALIDATEUR INT NULL,
   ID_CRITERE INT NOT NULL,
   TITRE_SIGNALEMENT VARCHAR(100) NOT NULL,
   DESCRIPTION LONGTEXT NOT NULL,
   DATE_FAITS DATETIME NOT NULL,
   LIEU_SIGNALEMENT VARCHAR(255) NOT NULL,
   DATE_SIGNALEMENT DATETIME DEFAULT CURRENT_TIMESTAMP,
   STATUT VARCHAR(30) NOT NULL DEFAULT 'SOUMIS',
   REPONSE_ETUDIANT LONGTEXT NULL,
   DATE_REPONSE DATETIME NULL,
   DECISION LONGTEXT NULL,
   DATE_DECISION DATETIME NULL,
   DATE_AUDITION DATETIME NULL,
   NOTES_AUDITION LONGTEXT NULL,
   CONSEIL_DISCIPLINE TINYINT(1) NOT NULL DEFAULT 0,
   CONSTRAINT FK_DECLARER_ETU FOREIGN KEY (ID_PERSONNE_ETUDIANT) REFERENCES ETUDIANT (ID_PERSONNE),
   CONSTRAINT FK_SIGNALEMENT_AUTEUR FOREIGN KEY (ID_PERSONNE_AUTEUR) REFERENCES PERSONNE (ID_PERSONNE),
   CONSTRAINT FK_VALIDER_ADMIN FOREIGN KEY (ID_PERSONNE_VALIDATEUR) REFERENCES PERSONNE (ID_PERSONNE) ON DELETE SET NULL,
   CONSTRAINT FK_SIGNALEMENT_CRITERE FOREIGN KEY (ID_CRITERE) REFERENCES CRITERE (ID_CRITERE)
) ENGINE=InnoDB;

-- 20. TEMOIN
CREATE TABLE TEMOIN (
   ID_TEMOIN INT AUTO_INCREMENT PRIMARY KEY,
   ID_SIGNALEMENT INT NOT NULL,
   NOM_TEMOIN VARCHAR(50) NOT NULL,
   PRENOM_TEMOIN VARCHAR(50) NOT NULL,
   CONTACT_TEMOIN VARCHAR(50),
   CONSTRAINT FK_IMPLIQUER FOREIGN KEY (ID_SIGNALEMENT) REFERENCES SIGNALEMENT (ID_SIGNALEMENT) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 20b. SIGNALEMENT_HISTORIQUE
CREATE TABLE SIGNALEMENT_HISTORIQUE (
   ID_HISTORIQUE INT AUTO_INCREMENT PRIMARY KEY,
   ID_SIGNALEMENT INT NOT NULL,
   STATUT VARCHAR(30) NOT NULL,
   ID_PERSONNE INT NULL,
   DATE_CHANGEMENT DATETIME DEFAULT CURRENT_TIMESTAMP,
   COMMENTAIRE VARCHAR(255) NULL,
   CONSTRAINT FK_HISTO_SIGNALEMENT FOREIGN KEY (ID_SIGNALEMENT) REFERENCES SIGNALEMENT (ID_SIGNALEMENT) ON DELETE CASCADE,
   CONSTRAINT FK_HISTO_PERSONNE FOREIGN KEY (ID_PERSONNE) REFERENCES PERSONNE (ID_PERSONNE) ON DELETE SET NULL
) ENGINE=InnoDB;

-- 21. PIECE_JUSTIFICATIVE
CREATE TABLE PIECE_JUSTIFICATIVE (
   ID_PIECE INT AUTO_INCREMENT PRIMARY KEY,
   ID_SIGNALEMENT INT NOT NULL,
   NOM_FICHIER VARCHAR(100) NOT NULL,
   CHEMIN_FICHIER VARCHAR(255) NOT NULL,
   TYPE_FICHIER VARCHAR(50) NOT NULL,
   DATE_AJOUT DATETIME DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT FK_JOINDRE FOREIGN KEY (ID_SIGNALEMENT) REFERENCES SIGNALEMENT (ID_SIGNALEMENT) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 22. MOUVEMENT_POINTS
-- Registre immuable : aucune modification ni suppression, une correction = une écriture inverse.
-- NOMBRE_POINTS est toujours positif, le sens est donné par TYPE_MOUVEMENT (POSITIF / NEGATIF).
CREATE TABLE MOUVEMENT_POINTS (
   ID_MOUVEMENT INT AUTO_INCREMENT PRIMARY KEY,
   ID_CRITERE INT NOT NULL,
   ID_PERSONNE INT NOT NULL,
   NOMBRE_POINTS DECIMAL(5,2) NOT NULL,
   TYPE_MOUVEMENT VARCHAR(10) NOT NULL,
   DATE_MOUVEMENT DATETIME DEFAULT CURRENT_TIMESTAMP,
   MOTIF_MOUVEMENT VARCHAR(255),
   ID_SIGNALEMENT INT NULL,
   ID_VALIDATEUR INT NULL,
   ID_PRESENCE INT NULL,
   ID_MOUVEMENT_CORRIGE INT NULL,
   CONSTRAINT FK_MOTIVER FOREIGN KEY (ID_CRITERE) REFERENCES CRITERE (ID_CRITERE),
   CONSTRAINT FK_POINTS_ETUDIANT FOREIGN KEY (ID_PERSONNE) REFERENCES ETUDIANT (ID_PERSONNE),
   CONSTRAINT FK_POINTS_SIGNALEMENT FOREIGN KEY (ID_SIGNALEMENT) REFERENCES SIGNALEMENT (ID_SIGNALEMENT),
   CONSTRAINT FK_POINTS_VALIDATEUR FOREIGN KEY (ID_VALIDATEUR) REFERENCES PERSONNE (ID_PERSONNE) ON DELETE SET NULL,
   CONSTRAINT FK_POINTS_PRESENCE FOREIGN KEY (ID_PRESENCE) REFERENCES PRESENCE (ID_PRESENCE),
   CONSTRAINT FK_POINTS_CORRIGE FOREIGN KEY (ID_MOUVEMENT_CORRIGE) REFERENCES MOUVEMENT_POINTS (ID_MOUVEMENT)
) ENGINE=InnoDB;

-- 23. RESULTAT_SEMESTRIEL
-- STATUT_VALIDATION : PROVISOIRE, CLOTURE
CREATE TABLE RESULTAT_SEMESTRIEL (
   ID_RESULTAT INT AUTO_INCREMENT PRIMARY KEY,
   ID_SEMESTRE INT NOT NULL,
   ID_PERSONNE INT NOT NULL,
   NOTE_PROVISOIRE DECIMAL(4,2) NOT NULL DEFAULT 20.00,
   NOTE_FINALE DECIMAL(4,2) NULL,
   MENTION VARCHAR(50),
   STATUT_VALIDATION VARCHAR(100) NOT NULL DEFAULT 'PROVISOIRE',
   DATE_CLOTURE DATETIME NULL,
   CONSTRAINT FK_GENERER FOREIGN KEY (ID_SEMESTRE) REFERENCES SEMESTRE (ID_SEMESTRE),
   CONSTRAINT FK_RESULTAT_ETUDIANT FOREIGN KEY (ID_PERSONNE) REFERENCES ETUDIANT (ID_PERSONNE),
   CONSTRAINT UQ_RESULTAT UNIQUE (ID_SEMESTRE, ID_PERSONNE),
   CONSTRAINT CK_NOTE_PROVISOIRE CHECK (NOTE_PROVISOIRE BETWEEN 0 AND 20),
   CONSTRAINT CK_NOTE_FINALE CHECK (NOTE_FINALE IS NULL OR NOTE_FINALE BETWEEN 0 AND 20)
) ENGINE=InnoDB;

-- 24. JOURNAL_CONNEXION
-- Sert aussi de journal d'audit : ACTION / DETAILS sont renseignés pour les opérations sensibles.
CREATE TABLE JOURNAL_CONNEXION (
   ID_JOURNAL INT AUTO_INCREMENT PRIMARY KEY,
   ID_PERSONNE INT NOT NULL,
   DATE_CONNEXION DATETIME DEFAULT CURRENT_TIMESTAMP,
   ADRESSE_IP VARCHAR(50) NOT NULL,
   STATUT VARCHAR(20) NOT NULL,
   ACTION VARCHAR(100) NULL,
   DETAILS VARCHAR(255) NULL,
   CONSTRAINT FK_TRACER_PERSONNE FOREIGN KEY (ID_PERSONNE) REFERENCES PERSONNE (ID_PERSONNE) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 24b. TENTATIVE_CONNEXION
-- Échecs de connexion récents, par identifiant saisi et par adresse : limite les essais de mot de passe.
CREATE TABLE TENTATIVE_CONNEXION (
   ID_TENTATIVE INT AUTO_INCREMENT PRIMARY KEY,
   IDENTIFIANT VARCHAR(100) NOT NULL,
   ADRESSE_IP VARCHAR(50) NOT NULL,
   DATE_TENTATIVE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   INDEX IDX_TENTATIVE_IDENTIFIANT (IDENTIFIANT, DATE_TENTATIVE),
   INDEX IDX_TENTATIVE_ADRESSE (ADRESSE_IP, DATE_TENTATIVE)
) ENGINE=InnoDB;

-- 25. PARAMETRE_SYSTEME
CREATE TABLE PARAMETRE_SYSTEME (
   CODE_PARAMETRE VARCHAR(50) PRIMARY KEY,
   VALEUR VARCHAR(50) NOT NULL,
   DESCRIPTION VARCHAR(255)
) ENGINE=InnoDB;
